### ISSUE TITLE
Tweet button on mobile

### ISSUE THREAD

**Issue by SiggeSax** [Swetugg/swetugg-web#125]
There is no tweet button on the speakers sites, only a link with the text "Tweet" which is positioned weirdly. 
![temp](https://user-images.githubusercontent.com/50992486/68776587-a1bdf880-0630-11ea-85b6-fc22c8875349.png)

**Comment by andlju** [comment]
Which platform is this on? Looks good on Chrome/Safari on iOS at least.

**Comment by SiggeSax** [comment]
Firefox on Android

**Comment by ceciliasharp** [comment]
tweet button removed on the new speaker site that are about to be publiched
