### ISSUE TITLE
Update color schema

### ISSUE THREAD

**Issue by iloabn** [Swetugg/swetugg-web#37]
Having some serious issues with the RC + Preview software so can't really edit the site at the moment.
But the new color schema that should be used (for 2016) is:

@primary: #A30046;
@dark: #524149;
@light: #F2FCFF;
@offlight: #FFF7FA;
@highlight: #7AD4E5;

**Comment by Yonjuro** [comment]
This change to variables.less was commited 2015-07-28 by Anders
