### ISSUE TITLE
Speaker view is missing

### ISSUE THREAD

**Issue by devlead** [Swetugg/swetugg-web#43]
you probably just haven't gotten around to it yet, but `public ActionResult Speaker(string speakerSlug)` in [src\Swetugg.Web\Areas\Swetugg2016\Controllers\ConferenceController.cs](https://github.com/Swetugg/swetugg-web/blob/master/src/Swetugg.Web/Areas/Swetugg2016/Controllers/ConferenceController.cs)  will fail as there's no matching view for it.

**Comment by andlju** [comment]
Yep, since we don't have any speakers confirmed yet it hasn't been much of a priority. ;)

**Comment by andlju** [comment]
Fixed some time ago..
