### ISSUE TITLE
ApplicationDbContext database initializer strategy

### ISSUE THREAD

**Issue by devlead** [Swetugg/swetugg-web#46]
For the database to be created as stated in [README.md](https://github.com/Swetugg/swetugg-web/blob/master/README.md) the [ApplicationDbContext.cs#L30](https://github.com/Swetugg/swetugg-web/blob/master/src/Swetugg.Web/Models/ApplicationDbContext.cs#L30) probably needs to be CreateDatabaseIfNotExists.

I'm new to the code base, maybe strategy should be configurable?

**Comment by andlju** [comment]
Yes, I think I rememver having to change to strategy for it to make sense in production.. Making it configurable sounds like a better idea.
